name: Check for release

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string

jobs:
  check_for_release:
    if: startsWith(inputs.title, 'Release')
    runs-on: macOS-13
    name: Check for release
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Check if neessary files are changed
        id: file-check
        run: |
          version=$(echo '${{ inputs.title }}' | grep -Eo '\d+\.\d+\.\d+')

          requiredFiles=(
            "Test/Constants.swift" 
            "test.podspec" 
            "Changelogs/$version.md" 
          )

          for file in ${requiredFiles[@]}; do
            if [[ " ${{ steps.changed-files.outputs.all_changed_files }} " =~ " ${file} " ]]; then
              echo "$file was changed"
            else
              echo "::error::$file wasn't added/updated, but is required for release"
              exit 1
            fi
          done