name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to be released (e.g. "2.5.0")'
        required: true
      changelog:
        description: 'The changelog for new version'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch "main" # TODO: Change to master
        uses: actions/checkout@v2
        with:
          ref: 'main' # TODO: Change to master

      - name: Create and push git tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Release version
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: ${{ inputs.version }}
          body: ${{ inputs.changelog }}
          draft: false
          prerelease: false
