name: Run unit tests

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  unit_tests:
    if: github.event.pull_request.merged == false
    runs-on: macOS-13
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: | 
          xcodebuild test -scheme Test -resultBundlePath TestResults -destination 'platform=iOS Simulator,name=iPhone 14' && exit ${PIPESTATUS[0]}

  check_for_release:
    if: startsWith(github.event.pull_request.title, 'Release')
    runs-on: macOS-13
    name: Check for release
    steps:
      - uses: actions/checkout@v4
      - id: check_for_release
        uses: ./.github/actions/check_for_release.yaml
        with:
          title: ${{ github.event.pull_request.title }}
      
      - run: echo "Prepared"
        if: steps.check_for_release.outputs.prepared == true
        
      - run: |
          echo "::error::$file wasn't added/updated, but is required for release"
          exit 1
        if: steps.check_for_release.outputs.prepared == false