name: Run unit tests

on: pull_request

jobs:
  test:
    runs-on: macos-13
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: | 
          xcodebuild test -scheme Test -resultBundlePath TestResults -destination 'platform=iOS Simulator,name=iPhone 14' 

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()

  # check_for_release:
  #   runs-on: ubuntu-latest