name: Run unit tests

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
# NOTE: Disabled unit tests to speedup process
  # unit_tests:
  #   if: github.event.pull_request.merged == false
  #   runs-on: macOS-13
  #   name: Run unit tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Test
  #       run: | 
  #         xcodebuild test -scheme Test -resultBundlePath TestResults -destination 'platform=iOS Simulator,name=iPhone 14' && exit ${PIPESTATUS[0]}

  check_for_release:
    if: startsWith(github.event.pull_request.title, 'Release')
    # if: github.event.pull_request.merged && startsWith(github.event.pull_request.title, 'Release')
    runs-on: ubuntu-latest
    name: Check for release
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Check if neessary files are changed
        id: file-check
        run: |
          echo "{passed}={true}" >> $GITHUB_OUTPUT

          requiredFiles=(
            "Test/Constants.swift" 
            "test.podspec" 
            "Changelogs/2.5.1.md" 
          )

          for file in ${requiredFiles[@]}; do
            if [[ " ${{ steps.changed-files.outputs.all_changed_files }} " =~ " ${file} " ]]; then
              echo "$file was changed"
            else
              echo "{passed}={false}" >> $GITHUB_OUTPUT
            fi
          done

      - name: Check outputs
        run: echo ${{ steps.file-check.outputs.passed }}

      # - name: Try to fail
      #   run: exit 1
