name: Run unit tests

on: pull_request

jobs:
  test:
    runs-on: macos-13
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: | 
          xcodebuild -scheme Test -resultBundlePath TestResults test

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()

  # check_for_release:
  #   runs-on: ubuntu-latest